### ISSUE TITLE
Telnet connection failed

### ISSUE THREAD

**Issue by SebastienDandrifosse** [kebasaa/FLIR-A320-control#3]
Hello kebasaa,
Thank you for this control app. 
I face the following error message with a A320 camera :  "no connection could be made because the target machine actively refused it" when using tn = telnetlib.Telnet(host, port, timeout)
The IP is right because with a random IP I get timeout. I already checked the firewalls. 
Do you have any idea of the cause of this problem ? Did you ever face a similar issue ?

Thank you in advance for any help/suggestion

Best regards

**Comment by kebasaa** [comment]
Hi Sebastien

That's really strange, I've never had that problem. Could it be that your telnet connection is password protected, i.e. is a telnet password set? If yes, the easiest option would be to reset it. In fact, I'd recommend that you do a factory reset of the camera. Let me know how things go after that.

Regards

**Comment by SebastienDandrifosse** [comment]
Hi,
Thank you for this quick answer. I found a solution using flir IP config to detect the IP at several times. Somehow, the IP of the camera changed while camera remained connected (with cross ethernet cable) to the computer. I cannot explain the phenomenon (my knoweldge of that kind of connection is limited) but my advice would be to always check the IP with IP config (provided by flir). 

Best regards

**Comment by kebasaa** [comment]
My preferred solution is to put a router between the computer and the camera. Then, set a fixed IP using the MAC address of the camera. Otherwise, every time the camera reboots (It has a built-in Windows), it will get a new IP address
